### ISSUE TITLE
Fetch entities doesn't work

### ISSUE THREAD

**Issue by juslex** [guimatheus92/node-red-homeassistant-three-way#8]
Olá, atualizei novamente para a última versão, rodei o container docker e aplicação rodou normalmente. Adaptei o código de template conforme código abaixo para listar as entidades de acordo com a minha nomenclatura, conseguir com sucesso na aba template em ferramentas de desenvolvedor do home assistant extrair a lista de entidades. Chequei e revisei o endereço do home assistant, o token e o código de template nas configurações da interface da aplicação, contudo, obtenho o mesmo erro todas vez:

{%- set mqtt_entities = expand(integration_entities('mqtt')) -%}
{%- for entity in mqtt_entities -%}
  {%- set entity_name = state_attr(entity.entity_id, 'friendly_name') or entity.entity_id -%}
  {%- set last_seen = state_attr(entity.entity_id, 'last_seen') -%}
  {%- set indicator_mode = state_attr(entity.entity_id, 'indicator_mode') -%}
  {%- if ('interruptor' in entity_name|lower or 'switch' in entity_name|lower) and 
        'cenas' not in entity_name|lower and 
        'last_seen' not in entity_name|lower and 
        last_seen is none and 
        indicator_mode is none -%}
    {%- if 'Backlight' not in entity_name and 
          'Power' not in entity_name and 
          'number' not in entity.entity_id -%}
      [{{ entity_name }}, {{ entity.entity_id }}]
    {%- endif -%}
  {%- endif -%}
{%- endfor -%}

Print do erro

<img width="886" alt="Captura de Tela 2024-07-28 às 14 50 17" src="https://github.com/user-attachments/assets/d214577f-2928-46fa-b843-41414bf7a200">

**Comment by guimatheus92** [comment]
Poderia enviar um print do resultado do seu código lá na aba Template do HA?

Poderia enviar um print de como está a sua página `Settings` por favor? 

Além disso, consegue entrar no seu container no Docker e tirar um print de como está o arquivo `config.yaml`?

Quanto mais conteúdo na issue, é mais facil pra eu poder entender como está cada etapa.

**Comment by juslex** [comment]
Olá, consegui identificar o erro. Seria bom atualizar o readme com isso. O erro de autenticação do token de longa duração ocorria quando usava o meu usuário que necessita de autenticação de dois fatores para o login. Então criei outro usuário no home assistant sem habilitar o 2FA e criei um token de longa duração, nesse cenário a aplicação logou e extraiu as entidades de acordo com o template modificado que eu coloquei.

**Comment by guimatheus92** [comment]
Por conta disso, eu to adicionando um botão de Testar Conexão dentro da própria plataforma, para facilitar para o usuário.

Porém eu estava dando uma olhada no Home Assistant aqui pra ver essa questão de 2FA. Você criou um novo usuário na aba "Usuários"? Qual foi o processo?

Porque pelo que eu vi, o Token não é associado a um usuário especifico certo? Por isso estou na duvida.

**Comment by guimatheus92** [comment]
Só por via das duvidas, conseguiu gerar o mapping e importar no NodeRED afinal das contas?

**Comment by juslex** [comment]
Eu consegui pegar as entidades, mas preciso refinar o template, pois algumas entidades que gostaria não apareceram. Fica como sugestão de upgrade futuro, algum frontend para que ele já gere o template com as informações das entidades que deseja importar. Quanto ao token, eu olhei a documentação e lá dava margem a isso que você falou., no entanto, ao criar um novo usuário e sem 2FA e gerando o token logado nele, funcionou.
